# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b01f7045b3ca49311dd64918332b97bd"
name = "learning-app-devlopment"
application_url = "https://client-auto-fulfillment-routing-for.onrender.com"
embedded = true

[access_scopes]
scopes = "read_locations,read_orders,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/orders_create"
  topics = [ "orders/create" ]

[auth]
redirect_urls = [ "https://client-auto-fulfillment-routing-for.onrender.com/auth/callback" ]

[build]
automatically_update_urls_on_dev = false
